run:
		python manage.py runserver

rene:
		python manage.py makemigrations
		python manage.py migrate

delmig:
		rm -rf ./apps/cages/migrations/00*.py
		rm -rf ./apps/farms/migrations/00*.py
		rm -rf ./apps/markets/migrations/00*.py
		rm -rf ./apps/profiles/migrations/00*.py
		rm -rf ./apps/rabbits/migrations/00*.py
		rm -rf ./apps/users/migrations/00*.py

