# Generated by Django 4.2.6 on 2023-10-12 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_cages", "0001_initial"),
        ("farms", "0001_initial"),
        ("apps_rabbits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_producer", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=15, null=True)),
                ("photo", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "qualification",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("cage_id", models.ManyToManyField(to="apps_cages.cage")),
                ("farm_id", models.ManyToManyField(to="farms.farm")),
                ("rabbit_id", models.ManyToManyField(to="apps_rabbits.rabbit")),
            ],
        ),
    ]
