# Generated by Django 4.2.6 on 2023-10-06 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
