# Generated by Django 4.2.6 on 2023-10-10 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rabbit",
            name="cage_id",
        ),
        migrations.DeleteModel(
            name="Cage",
        ),
        migrations.DeleteModel(
            name="Rabbit",
        ),
    ]
