# Generated by Django 4.2.6 on 2023-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="addresses",
        ),
    ]
