# Generated by Django 4.2.6 on 2023-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_addresses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="city_id",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="state_id",
            new_name="state",
        ),
    ]
