# Generated by Django 4.2.6 on 2023-10-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_rabbits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rabbit",
            name="photo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rabbit",
            name="genre",
            field=models.CharField(
                choices=[("Macho", "Macho"), ("Hembra", "Hembra")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="rabbit",
            name="weight",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
