# Generated by Django 4.2.6 on 2023-10-19 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("apps_rabbits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rabbit",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
