# Generated by Django 4.2.6 on 2023-10-20 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("apps_rabbits", "0002_rabbit_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rabbit",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
