# Generated by Django 4.2.6 on 2023-10-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_cages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="photo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cage",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
